/**
 * Representa um usuario generico no sistema bbsys.
 * 
 */
package br.com.bbsys.model.usuario;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "Usuario", catalog = "testehibernate")
public class Usuario implements java.io.Serializable {

	private Long id;
	private String email;
	private String nome;
	private String cidade;
	private Date dataCadastro;
	private Date dataNascimento;
	private Integer estado;
	private Integer pais;
	private String senha;
	private String sexo;
	private Integer telefone;
	private Integer tipoUsuario;

	public Usuario() {
	}

	public Usuario(String email, String nome, String cidade, Date dataCadastro,
			Date dataNascimento, Integer estado, Integer pais, String senha,
			String sexo, Integer telefone, Integer tipoUsuario) {
		this.email = email;
		this.nome = nome;
		this.cidade = cidade;
		this.dataCadastro = dataCadastro;
		this.dataNascimento = dataNascimento;
		this.estado = estado;
		this.pais = pais;
		this.senha = senha;
		this.sexo = sexo;
		this.telefone = telefone;
		this.tipoUsuario = tipoUsuario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "cidade")
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataCadastro", length = 19)
	public Date getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataNascimento", length = 19)
	public Date getDataNascimento() {
		return this.dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	@Column(name = "estado")
	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	@Column(name = "pais")
	public Integer getPais() {
		return this.pais;
	}

	public void setPais(Integer pais) {
		this.pais = pais;
	}

	@Column(name = "senha")
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@Column(name = "sexo")
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "telefone")
	public Integer getTelefone() {
		return this.telefone;
	}

	public void setTelefone(Integer telefone) {
		this.telefone = telefone;
	}

	@Column(name = "tipoUsuario")
	public Integer getTipoUsuario() {
		return this.tipoUsuario;
	}

	public void setTipoUsuario(Integer tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

}